"""add_preferences_and_extra_data

Revision ID: 700e9863ffe6
Revises: 96139bee0665
Create Date: 2026-07-15 19:27:09.600314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700e9863ffe6'
down_revision: Union[str, None] = '96139bee0665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_findings', sa.Column('extra_data', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferences')
    op.drop_column('review_findings', 'extra_data')
    # ### end Alembic commands ###
