"""Add advanced metrics

Revision ID: 96139bee0665
Revises: 1a2b3c4d5e6f
Create Date: 2026-07-15 18:13:42.419642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96139bee0665'
down_revision: Union[str, None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('reviews', sa.Column('pylint_score', sa.String(length=10), nullable=True))
    op.add_column('reviews', sa.Column('bandit_summary', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('maintainability_index', sa.String(length=20), nullable=True))
    op.add_column('reviews', sa.Column('cyclomatic_complexity', sa.String(length=20), nullable=True))
    op.add_column('reviews', sa.Column('ai_score', sa.String(length=10), nullable=True))
    op.add_column('reviews', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('documentation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'documentation')
    op.drop_column('reviews', 'ai_summary')
    op.drop_column('reviews', 'ai_score')
    op.drop_column('reviews', 'cyclomatic_complexity')
    op.drop_column('reviews', 'maintainability_index')
    op.drop_column('reviews', 'bandit_summary')
    op.drop_column('reviews', 'pylint_score')
    op.drop_column('projects', 'file_path')
    # ### end Alembic commands ###
